name: Update Rule Data

on:
    schedule:
        -   cron: '0 0 * * *'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        types:
            - auto_merge_enabled
            - closed

jobs:
    update:
        runs-on: self-hosted
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 1
            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17
                run: |
                    go mod tidy
            -   name: Update Rule Data
                with:
                  go-version: 1.17
                run: |
                    go run -v ./cmd/.
            -   name: commit
                run: |
                    git config --global user.email darabuchi0818@gmail.com
                    git config --global user.name "“だらぶち"
                    git add .
                    git commit -a -m "update rule data"
            -   name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
